### PR TITLE
SBT Launcher update 1.0.0

### PR DESCRIPTION
**Pull request by MrOutis**
- Use wget instead of curl (avoiding certificate errors)
- Let the user choose directories

*Tested on Ubuntu 15.04 & 14.04.3*

### CODE REVIEW

**Comment by eed3si9n** [comment]
Partly duplicate of #75

**Comment by mismatch** [comment]
sbt 0.13.9 has been already released. It would be better to update to latest version.

**Comment by MrOutis** [comment]
Don't merge it yet, I missed a commit

**Comment by MrOutis** [comment]
Done. :ok:

**Comment by eed3si9n** [comment]
sbt project split up the launcher project into sbt/launcher, so maybe it's better to use launcher 1.0.0 JAR. This is binary compatible with current sbt 0.13 series, and we will keep binary compatibility for the next major version sbt 1.0 as well:
https://oss.sonatype.org/content/repositories/public/org/scala-sbt/launcher/1.0.0/launcher-1.0.0.jar

**Comment by MrOutis** [comment]
Yeah, sounds great!

**Comment by eed3si9n** [comment]
Could you rebase against the master?

**Comment by MrOutis** [comment]
I don't know if I did it right. Sorry if I did a mess :disappointed:

**Comment by eed3si9n** [comment]
The part about the launcher JAR looks ok, but I'd like to hear what @n8han thinks about letting the user choose directories in `setup.sh`.

**Comment by eed3si9n** [comment]
Asking the user where to put things is actually misleading because the directory the user entered is not honored by the conscript Scala application. I'm going to change this slightly and allow the user specify environment variables, and ask the user if the default value is ok: Y/n

**Comment by MrOutis** [comment]
Sounds good, @eed3si9n, the `[Y/n]` prompt is pretty common :+1:

**Pull request merged**
